DB setup and custom user model creation
rohanboopathiraj/fixify pull request #1
Opened 2024-11-16 09:46 UTC by rohanboopathiraj

DB setup and create a custom user model for fixify users.

2024-11-16 09:48 UTC, ruban072001 requested changes

2024-11-16 09:48 UTC, ruban072001 commented on src/accounts/models.py
> +
Make sure these fields are enough.

2024-11-16 12:15 UTC, rohanboopathiraj commented on src/accounts/models.py
> +
this will be handled in login and register route

2024-11-17 07:50 UTC, ruban072001 approved these changes

2024-11-17 07:51 UTC, merged